spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: gajuMith1!
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto:none
    show-sql: true

paypal:
  apiUrl: http://api.paypal.com
  timeout: 3000
  enabled: true
  currencies: USD, INR

paymentGateway: abc

notification:
  mailServer: https://smtp.gmail.com
  port: 531